### ISSUE TITLE
Issue when running "litellm --config ./litellm_config.yaml"

### ISSUE THREAD

**Issue by Looperswag** [Intelligent-Internet/ii-researcher#5]
![Image](https://github.com/user-attachments/assets/dc5a07cd-a487-4cb8-bde2-ebbbebc9a546)

**Comment by khongtrunght** [comment]
@Looperswag It looks like you're encountering a YAML parsing error in your LiteLLM config file. The error message yaml.scanner.ScannerError: mapping values are not allowed here typically indicates incorrect indentation or structure in your YAML file. Could you show me the outline of the config file

**Comment by Looperswag** [comment]
> [@Looperswag](https://github.com/Looperswag) It looks like you're encountering a YAML parsing error in your LiteLLM config file. The error message yaml.scanner.ScannerError: mapping values are not allowed here typically indicates incorrect indentation or structure in your YAML file. Could you show me the outline of the config file

sure, I copied code in your codec, and here it goes like:

**Comment by khongtrunght** [comment]
This is the bash command. You should run it in a terminal-like environment to create the file. But if you try to create the file manually, you should use something like this:

```yaml
model_list:
  - model_name: gpt-4o
    litellm_params:
      model: azure/gpt-4o
      api_base: ...
      api_key: ...
      api_version: 2024-12-01-preview
  - model_name: text-embedding-3-large
    litellm_params:
      model: azure/text-embedding-3-large
      api_base: ...
      api_key: ...
  - model_name: gemini-lite
    litellm_params:
      model: gemini/gemini-2.0-flash-lite
      api_key: ...
  - model_name: r1
    litellm_params:
      model: openai/deepseek-reasoner
      api_base: ...
      api_key: ...
litellm_settings:
  drop_params: true
```

You can check [LiteLLM Proxy Configs](https://docs.litellm.ai/docs/proxy/configs) for more detail.
